export const MAX_LENGTH_IMAGE_PRODUCT_GALLERY = 6
export const MAX_LENGTH_IMAGE_PRODUCT_GALLERY_THUMBNAIL = 1

export const MAX_LENGTH_VIDEO_PRODUCT = 1


export const MAX_LENGTH_IMAGE_MEDIA = 1
export const MAX_LENGTH_VIDEO_MEDIA = 1
